name: Build and perform unit and functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build_mimblewimble_coin:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      flags: "DEBUG=1"
      upload_app_binaries_artifact: "mimblewimble_coin_binary"

  build_mimblewimble_coin_floonet:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      flags: "DEBUG=1 CURRENCY=mimblewimble_coin_floonet"
      upload_app_binaries_artifact: "mimblewimble_coin_floonet_binary"

  job_functional_test:
    name: Functional test
    needs:
      - build_mimblewimble_coin
      - build_mimblewimble_coin_floonet
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/speculos:latest
      options: --entrypoint /bin/bash

    strategy:
      fail-fast: false
      matrix:
        network: [mimblewimble_coin, mimblewimble_coin_floonet]
        model: [nanox, nanos2, stax, flex]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update -q
          apt-get install -qy curl netcat-traditional nodejs npm
          npm install @ledgerhq/hw-transport-node-speculos

      - name: Download built app artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.network }}_binary
          path: build

      - name: Run Speculos
        id: start_speculos
        run: |
          binary_path="build/${{ matrix.model }}/bin/app.elf"
          /speculos/speculos.py --display headless \
            --seed "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" \
            "$binary_path" 2>speculos.log &

          echo $! > /tmp/speculos.pid

          timeout 10 sh -c 'until nc -z 127.0.0.1 9999; do sleep 1; done'

      - name: Run functional test
        run: |
          node tests/functional_tests/main.js \
            ${{ matrix.network }} speculos ${{ matrix.model }}

      - name: Upload Speculos log on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: speculos-${{ matrix.network }}-${{ matrix.model }}-log
          path: speculos.log

      - name: Kill Speculos
        run: |
          kill -9 $(cat /tmp/speculos.pid)

  job_unit_test:
    name: Unit test
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y libssl-dev

      - name: Build unit tests
        run: |
          cmake -Btests/unit_tests/build -Htests/unit_tests/ && make -C tests/unit_tests/build/

      - name: Run unit tests
        run: |
          make -C tests/unit_tests/build test
